### ISSUE TITLE
FastAPI UI not appearing

### ISSUE THREAD

**Issue by alexjj** [talkpython/modern-apis-with-fastapi#1]
Just starting out with your course and I noticed that the "UI" in the browser isn't working. I say "UI" as not sure how to describe it but screenshots should hopefully work:

What I get (no menu/interface):
![image](https://user-images.githubusercontent.com/440939/102775706-4444c100-4385-11eb-9086-a4f3343c6911.png)

Versus what I see in your videos (options to show raw data or formatted):
![image](https://user-images.githubusercontent.com/440939/102775812-8110b800-4385-11eb-8c4c-e7e8edf9d0b7.png)

I've tried searching for the problem, but I'm not using the right terminology as all that comes up is about the docs UI. This works fine, if I go to http://127.0.0.1:8000/docs. Other results suggest it's something to do with Swagger-UI but that doesn't get installed so not sure about that one.

Here's my venv:
![image](https://user-images.githubusercontent.com/440939/102776047-f5e3f200-4385-11eb-81f4-c2656ba35307.png)

Installed from requirements.txt:

```
fastapi
uvicorn
```

Any pointers in the right direction would be appreciated. It doesn't really affect the course but just stood out and I was curious.

My code:

```python
from typing import Optional

import fastapi
import uvicorn

api = fastapi.FastAPI()


@api.get('/')
def index():
    body = "<html>" \
           "<body style='padding: 10px;'>" \
           "<h1>Welcome to the API</h1>" \
           "<div>" \
           "Try it: <a href='/api/calculate?x=7&y=11'>/api/calculate?x=7&y=11</a>" \
           "</div>" \
           "</body>" \
           "</html>"

    return fastapi.responses.HTMLResponse(content=body)


@api.get('/api/calculate')
def calculate(x: int, y: int, z: Optional[int] = None):
    if z == 0:
        return fastapi.responses.JSONResponse(content={"error": "ERROR: Z cannot be zero."}, status_code=400)

    value = (x + y)

    if z is not None:
        value /= z

    return {
        'x': x,
        'y': y,
        'z': z,
        'value': value
    }


uvicorn.run(api, port=8000, host="127.0.0.1")
```

**Comment by mikeckennedy** [comment]
Hi @alexjj That is the native view of JSON data in Firefox. I don't think other browsers show it that way. Just use Firefox and you'll have the same experience, but it doesn't matter much really.

**Comment by alexjj** [comment]
Ah! Thanks for the clarification. As you say, it doesn't matter but it was just made me wonder.
