### ISSUE TITLE
Expected type 'Union[Type[ASGI2Protocol]

### ISSUE THREAD

**Issue by KrunchMuffin** [talkpython/modern-apis-with-fastapi#11]
When calling `uvicorn.run(api)` I get this error in Python 3.9.6

> Expected type 'Union[Type[ASGI2Protocol], (Union[HTTPScope, WebSocketScope, LifespanScope], () -> Awaitable[Union[HTTPRequestEvent, HTTPDisconnectEvent, WebSocketConnectEvent, WebSocketReceiveEvent, WebSocketDisconnectEvent, LifespanStartupEvent, LifespanShutdownEvent]], (Union[HTTPResponseStartEvent, HTTPResponseBodyEvent, HTTPServerPushEvent, HTTPDisconnectEvent, WebSocketAcceptEvent, WebSocketSendEvent, WebSocketResponseStartEvent, WebSocketResponseBodyEvent, WebSocketCloseEvent, LifespanStartupCompleteEvent, LifespanStartupFailedEvent, LifespanShutdownCompleteEvent, LifespanShutdownFailedEvent]) -> Awaitable[None]) -> Awaitable[None], str]', got 'FastAPI' instead

**Comment by mikeckennedy** [comment]
Hi. Can you send me the line of code where API is created?

Best,
Michael

Sent via Superhuman iOS ***@***.***>

**Comment by KrunchMuffin** [comment]
At first I tried it the way you had it `api = fastapi.FastAPI()` then I tried like in the docs. `api = FastAPI()` changing the import to reflect the update. `from fastapi import FastAPI`

**Comment by mikeckennedy** [comment]
Hi.

Both work. They just need to be internally consistent with the import statement:

- `import fastapi` => `api = fastapi.FastAPI()`
- `from fastapi import FastAPI` => `api = FastAPI()`

I personally prefer the more namespace driven approach for most code but either should work. The error looks like you might have written: `import fastapi` => `api = fastapi.FastAPI` (without `()`) the first time around.

**Comment by KrunchMuffin** [comment]
No, haven't done that. 
![image](https://user-images.githubusercontent.com/1037197/132136164-bb01b0db-3152-4678-a0f6-bd132fd95225.png)

**Comment by mikeckennedy** [comment]
Oh I see what's up. I just upgraded `uvicorn` to the latest version and that *warning* showed up. Someone screwed up the type hint in uvicorn and it thinks FastAPI won't run. But it runs fine. That's some PyCharm warning but if you run the code it still works. Not sure how to address that really other than saying just ignore it or add `# noinspection PyTypeChecker` on the line before.

**Comment by KrunchMuffin** [comment]
That's the thing, I can't get it to run.

![image](https://user-images.githubusercontent.com/1037197/132136529-64ecf2e5-3a89-430c-b453-af134113ca8f.png)

**Comment by mikeckennedy** [comment]
That is weird. Is should either crash or run but not do nothing. Exit code 0 is success. Can you add a print statement above that line to make sure it's actually running?

**Comment by mikeckennedy** [comment]
Oh, I see your error. You have:

`if __name__ == "__main":`

It should be:

`if __name__ == "__main__":`

Next time, just type `main` then tab to expand out the live template and it'll write the later version.

**Comment by KrunchMuffin** [comment]
LOL, i was just coming to post that.  THanks!
