### ISSUE TITLE
Runtime error when the fake data is supposed to be added

### ISSUE THREAD

**Issue by swedishmike** [talkpython/modern-apis-with-fastapi#2]
I'm afraid that I don't understand asyncio well enough to fix this myself so was wondering if I could get some help with this one?

In the code for Chapter 7 - inbound data, there is some fake data supposed to be added. When I try to run main.api it bombs out with a runtime error. As always there's lots of it but the pertinent bit seems to be:
```

  File "./main.py", line 53, in <module>
    configure()
  File "./main.py", line 20, in configure
    configure_fake_data()
  File "./main.py", line 45, in configure_fake_data
    asyncio.run(report_service.add_report("Misty sunrise today, beautiful!", loc))
  File "/Users/mike/.pyenv/versions/3.8.6/lib/python3.8/asyncio/runners.py", line 33, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'add_report' was never awaited
```
If I change the code not to call asyncio.run() and just call the functions it starts, but the fake data is not added at all.

I'm running Python v3.8.6 if that has any bearing.

Thanks for any ideas/hints and big thanks for a most excellent course!

**Comment by swedishmike** [comment]
I found how to make it run.

When I start it as `uvicorn main:api `it crashes out as per above. If I start it with `python main.py` instead it works just fine.

This should be good to close - but I was wondering if there is any reason why running it the former way doesn't work? Does it have to do with some imports or something possibly?

**Comment by mikeckennedy** [comment]
Hi. Glad you got it working and are enjoying the course. However, it should totally work BOTH ways. I'm sure there is a bug in your code that's just not being detected the way that uvicorn shuts down. Just search for `add_report(` and check two things:

First, that it's defined as `async def add_report(...)`.

Second, that everywhere you call it you do `await add_report(...)`. 

I'm guessing 1 is true, 2 is false. :)

**Comment by swedishmike** [comment]
Hi, many thanks for your reply.

I still can't get it to run, not even if I cheat and use your code straight from the repo.

If I try to change the following in `main.py` 

```
    asyncio.run(await report_service.add_report("Misty sunrise today, beautiful!", loc))
    asyncio.run(await report_service.add_report("Clouds over downtown.", loc))

```
I get a new error instead:
```
   asyncio.run(await report_service.add_report("Misty sunrise today, beautiful!", loc))
                ^
SyntaxError: 'await' outside async function

```
I also tried to add some awaits in the `add_report` session and an await to the return as per below but that didn't help either. 

```
# Simulate saving to the DB.
    # Would be an async call here.
    await asyncio.sleep(0)
    
    __reports.append(report)

    __reports.sort(key=lambda r: r.created_date, reverse=True)

    return await report

```

I'm currently working my way through your async course as well, but I've not used it enough to fix these errors, yet. :) 

Sorry to be a pain, but any further ideas? Does the code run in ch07 run as it is with 'uvicorn main:api' on your system?

As mentioned, I'm on Python 3.8.6 and I'm running it under Big Sur right now.

**Comment by swedishmike** [comment]
Possibly one step closer?

I played around and if I change the configure_fake_data function to become a async one as per below, it doesn't totally crash and burn.

```
async def configure_fake_data():
    # This was added to make it easier to test the weather event reporting
    # We have /api/reports but until you submit new data each run, it's missing
    # So this will give us something to start from.
    loc = Location(city="Portland", state="OR", country="US")
    asyncio.run(report_service.add_report("Misty sunrise today, beautiful!", loc))
    asyncio.run(report_service.add_report("Clouds over downtown.", loc))

```
I do however get a new error:

```
~/Pr/fa2/ch07-inbound-data  main !2 ❯ uvicorn main:api                    1m 34s  ch07-inbound-data  11:50:44
./main.py:20: RuntimeWarning: coroutine 'configure_fake_data' was never awaited
  configure_fake_data()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
INFO:     Started server process [63756]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

I'm not sure if I'm barking up the wrong tree here or not? I guess I could try and add some awaits like `await asyncio.sleep(0)` and make the other configure functions async but that could possibly lead me down an mahoosive rabbit hole.

Once again - sorry for being a pain.

**Comment by mikeckennedy** [comment]
Hi Mike,

So this error:

```
./main.py:20: RuntimeWarning: coroutine 'configure_fake_data' was never awaited
```

Means that wherever you're calling `configure_fake_data()` you're missing an await on that line.

I'm not sure about the difference but if you can reproduce the error maybe you could zip your code and share it with me to see if I can as well?

**Comment by swedishmike** [comment]
Hi Michael,

Many thanks for getting back to me again. So what I'm using right now is a clean copy of this repo.

To replicate the issue I initially reported I follow the following steps.

1. git clone the repo
2. change directory into  the ch07-inbound-data directory
3. create a virtual environment there 
4. add the necessary modules by  `pip install -r requirements.txt`
5. try to run it with `uvicorn main:api`

That generates the exception that ends with:

```
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'add_report' was never awaited
```

To get to the state where uvicorn starts and 'only' generates the  `./main.py:20: RuntimeWarning: coroutine 'configure_fake_data' was never awaited` error I do the following. 

1. Start with step 1 - 4 above (still based on the course code)
2. Change line 40 in main.py from `def configure_fake_data():` to `async def configure_fake_data():`

If I then try to follow your suggestion and add an `await` where `configure_fake_data()` is called (which is in the configure function) I get the following error:

```
    await configure_fake_data()
    ^
SyntaxError: 'await' outside async function
```

If I go one step further and 'convert' the configure function to a async one, as per below,  I then get the following error.

```
async def configure():
    configure_routing()
    configure_api_keys()
    await configure_fake_data()

```
```
./main.py:53: RuntimeWarning: coroutine 'configure' was never awaited
  configure()
```

As I keep going deeper down this particular rabbithole I then try to await the `configure` function:

```
if __name__ == '__main__':
    configure()
    uvicorn.run(api, port=8000, host='127.0.0.1')
else:
    await configure()

```
I end up with this error:

```
  File "./main.py", line 50
    await configure()
    ^
SyntaxError: 'await' outside function
```

Which is sort of where I think I'm possibly making far too many changes - where there might be an easier/better solution than what I'm doing?

Since it's only main.py that's getting changed from the 'course' repo I've just attached that rather than a full zip of the directories. I've gone as far as to where I get the second to last error. 

[main.zip](https://github.com/talkpython/modern-apis-with-fastapi/files/5762202/main.zip)

**Comment by mikeckennedy** [comment]
Ah, I see. Thanks for the extra info. Just don't run it that way or skip the starter data. :)  What I was doing in the course was this:

`python main.py`

What you're doing is 

`uvicorn main:api`

They should be basically equivalent but for some reason, the way uvicorn setups the asyncio is freaking out the asyncio.run(). Because if you run it via main.py it works fine. If you run it via uvicorn it fails.

The fake data is totally unneeded. So just delete that `configure_fake_data()` function and remove the call to it. I only added it so you'd see some data on the home page without rerunning and reentering the data in the client app. But if it's not working for you, just take it out, or start the app via `python main.py`.

**Comment by swedishmike** [comment]
I thought that might be the case but since I'm a curious (and stubborn) so-and-so I was wondering if there was any way around that issue. 

Many thanks for bearing with me and getting to the bottom of it. I'll just comment it out and live with the difference between calling it with `python` or directly via `uvicorn`. At least I know one thing to avoid if I plan to run stuff directly via `uvicorn`.

Once again - many thanks for the help!

**Comment by mikeckennedy** [comment]
No problem. I make some minor changes to make it run successfully the entire time. But I can't figure out why `loop.run_until_complete()` would cause a not-awaited error. Anyway, see the commit above for at least something that avoids the crash.

**Comment by swedishmike** [comment]
I guess it will have to do with some kind of initialisation or similar that uvicorn does that makes things go a bit out of whack. It's a weird one - definitely one of those that I will keep coming back to. Just because I'm stubborn. ;)

The fix does the job quite nicely though - no more crashes. Thanks for taking the time to look into it and working around it.

**Comment by mikeckennedy** [comment]
Thanks. If you figure out what's happen, do give us an update here. :)
